export const surpriseMePrompts = [
  'an armchair in the shape of an avocado',
  'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
  'teddy bears shopping for groceries in Japan, ukiyo-e',
  'an oil painting by Matisse of a humanoid robot playing chess',
  'panda mad scientist mixing sparkling chemicals, digital art',
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
  'an astronaut lounging in a tropical resort in space, vaporwave',
  'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
  'a stained glass window depicting a hamburger and french fries',
  'a pencil and watercolor drawing of a bright city in the future with flying cars',
  'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
  'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  'an oil pastel drawing of an annoyed cat in a spaceship',
  'a painting of a fox in the style of Starry Night',
  'a bowl of soup that looks like a monster, knitted out of wool',
  'A plush toy robot sitting against a yellow wall',
  'A synthwave style sunset above the reflecting water of the sea, digital art',
  'Two futuristic towers with a skybridge covered in lush foliage, digital art',
  'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
  'A comic book cover of a superhero wearing headphones',
  'A centered explosion of colorful powder on a black background',
  'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
  'A photo of a white fur monster standing in a purple room',
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  'A Samurai riding a Horse on Mars, lomography.',
  'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
  'A realistic photograph of a young woman with blue eyes and blonde hair',
  'A man standing in front of a stargate to another dimension',
  'Spongebob Squarepants in the Blair Witch Project',
  'A velociraptor working at a hotdog stand, lomography',
  'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
  'A BBQ that is alive, in the style of a Pixar animated movie',
  'A futuristic cyborg dance club, neon lights',
  'The long-lost Star Wars 1990 Japanese Anime',
  'A hamburger in the shape of a Rubik’s cube, professional food photography',
  'A Synthwave Hedgehog, Blade Runner Cyberpunk',
  'An astronaut encountering an alien life form on a distant planet, photography',
  'A Dinosaur exploring Cape Town, photography',
  'A Man falling in Love with his Computer, digital art',
  'A photograph of a cyborg exploring Tokyo at night, lomography',
  'Dracula walking down the street of New York City in the 1920s, black and white photography',
  'Synthwave aeroplane',
  'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
  'A Space Shuttle flying above Cape Town, digital art',
  'Generate a futuristic cityscape',
  'Create an otherworldly alien landscape',
  'Design a steampunk-inspired flying machine',
  'Produce a whimsical, talking animal character',
  'Generate a surreal underwater world',
  'Create a bustling, vibrant market scene',
  'Design an enchanting, hidden forest glen',
  'Produce an abstract, mind-bending artwork',
  'Generate a retro-futuristic space station',
  'Create an imaginative, magical castle',
  'Design a post-apocalyptic wasteland',
  'Produce a serene, zen-inspired garden',
  'Generate a whimsical, floating island',
  'Create a vibrant, colorful explosion of shapes',
  'Design a futuristic cyberpunk city',
  'Produce an ancient, mystical temple',
  'Generate a cozy, fairytale cottage in the woods',
  'Create an eerie, haunted mansion',
  'Produce a surreal, dreamlike portrait',
  'Generate a futuristic vehicle of your imagination',
  'Create an abstract representation of a dream',
  'Design a mythical, legendary creature',
  'Produce a tranquil, serene beach scene',
  'Generate an eerie, haunted forest',
  'Create an eerie, haunted forest',
  'Design a whimsical, colorful hot air balloon',
  'Produce a fantastical, towering waterfall',
  'Generate a cosmic, intergalactic nebula',
  'Create a detailed, ornate piece of jewelry',
  'Design a whimsical, colorful hot air balloon',
  'Produce a fantastical, towering waterfall',
  'Generate a sci-fi spaceship interior',
  'Create a mesmerizing, kaleidoscopic pattern',
  'Design an otherworldly, alien plant',
  'Produce a mesmerizing, intricate mandala',
  'Generate a futuristic, high-tech gadget',
  'Create a mysterious, ancient tome or book cover',
  'Design a surreal, floating island in the sky',
  'Produce a stunning, crystal-clear underwater scene',
  'Generate a wild, imaginative monster',
  'Create a serene, tranquil forest stream',
  'Design a whimsical, magical doorway to another world',
  'Produce an abstract representation of a feeling or emotion',
  'Generate a futuristic, sci-fi laboratory',
  'Create a whimsical, fairy tale carriage',
  'Design a stunning, otherworldly celestial body',
  'Produce a chaotic, energetic burst of colors',
  'Generate a futuristic, cybernetic character',
  'Create a mystical, ancient artifact',
  'Design a surreal, floating island made of books',
  'Produce an abstract, surreal self-portrait',
  'Generate a detailed, intricate city map',
  'Create a whimsical, flying fantasy creature',
];